[package]
name = "macro-extract"
version = "0.1.0"
edition = "2021"

[dependencies]
syn = {version = "2.0.72", features = ["full", "visit"]} 
notify-debouncer-full = "0.3.1"
notify = { version = "6.1.1" }
fs_extra = "1.3.0"
walkdir = "2.5.0"
quote = "1.0.36"
proc-macro2 = "1.0.86"
